---
# Bring stack down
- hosts: loadbalancer
  become: true
  tasks:
    - name: service nginx stop
      service: name=nginx state=stopped

    - name: port 80 drained
      wait_for: port=80 state=drained

- hosts: webserver
  become: true
  tasks:
     - name: service apache2 stop
       service: name=apache2 state=stopped

     - name: port 80 stop
       wait_for: port=80 state=stopped

# Restart mysql
- hosts: database
  become: true
  tasks:
     - name: service mysql restarted
       service: name=mysql state=restarted

     - name: wait for port 3306
       wait_for: host={{ ansible_eth1.ipv4.address }} port=3306 state=started

# Bring stack up
- hosts: webserver
  become: true
  tasks:
     - name: service apache2 start
       service: name=apache2 state=started

     - name: wait for port 80
       wait_for: port=80

- hosts: loadbalancer
  become: true
  tasks:
     - name: service nginx start
       service: name=nginx state=started

     - name: wait for port 80
       wait_for: port=80
