---
- hosts: all
  become: true
  tasks:
    - name: Remove useless pacakges from the cache
      apt:
         autoclean: yes

    - name: Remove dependencies that no longer required
      apt: 
         autoremove: yes  